# Generated by Django 6.1.1 on 2026-10-06 05:44

import catalog.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_phase2_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.PositiveIntegerField(blank=True, help_text='Low-stock threshold for this product. Empty uses the business setting.', null=True)),
                ('tracks_expiry', models.BooleanField(default=True, help_text='Batches of this product need an expiry date.')),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_path)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.product')),
            ],
            options={
                'verbose_name_plural': 'product batches',
                'ordering': ('expiry_date', 'batch_number'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.supplier'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['business', 'id'], name='brand_biz_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(models.F('business'), django.db.models.functions.text.Lower('name'), name='catalog_brand_unique_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['business', 'id'], name='category_biz_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('business'), django.db.models.functions.text.Lower('name'), name='catalog_category_unique_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['business', 'id'], name='productbatch_biz_id_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatch',
            index=models.Index(fields=['business', 'expiry_date'], name='batch_biz_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='catalog_batch_unique_number_per_product'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['business', 'id'], name='supplier_biz_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(models.F('business'), django.db.models.functions.text.Lower('name'), name='catalog_supplier_unique_name_per_business'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'id'], name='product_biz_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('business', 'sku'), name='catalog_product_unique_sku_per_business'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('business', 'barcode'), name='catalog_product_unique_barcode_per_business'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0), ('cost_price__gte', 0)), name='catalog_product_prices_not_negative'),
        ),
    ]
