# Generated by Django 6.1.1 on 2026-10-06 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_phase2_permissions'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Signed: positive adds stock, negative removes it.')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productbatch')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['business', 'id'], name='stockmovement_biz_id_idx'), models.Index(fields=['business', 'created_at'], name='movement_biz_created_idx'), models.Index(fields=['business', 'product', 'batch'], name='movement_biz_prod_batch_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inventory_movement_quantity_not_zero'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['SALE', 'DAMAGE', 'EXPIRY']), _negated=True), ('quantity__lt', 0), _connector='OR'), name='inventory_movement_outbound_is_negative'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'PURCHASE'), _negated=True), ('quantity__gt', 0), _connector='OR'), name='inventory_movement_purchase_is_positive')],
            },
        ),
    ]
