# Generated by Django 6.1.1 on 2026-10-10 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phase3_sales_permissions'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('EXPIRY', 'Expiry'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'RETURN'), _negated=True), ('quantity__gt', 0), _connector='OR'), name='inventory_movement_return_is_positive'),
        ),
    ]
