# Generated by Django 6.1.1 on 2026-10-10 05:39

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_phase3_sales_permissions'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(help_text='Receipt number, sequential per business.')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOID', 'Void')], default='COMPLETED', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of quantity × unit price, before discounts.', max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='What the customer owes for this sale: subtotal − discounts.', max_digits=12)),
                ('cost_total', models.DecimalField(decimal_places=2, help_text='COGS: sum of quantity × snapshotted unit cost.', max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.customer')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund')], default='PAYMENT', max_length=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash')], default='CASH', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount applied to the sale (always positive).', max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, help_text='Cash handed over by the customer.', max_digits=12)),
                ('change_given', models.DecimalField(decimal_places=2, default=0, help_text='Cash given back: amount_received − amount.', max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.sale')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Product selling price at the time of sale.', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount on the whole line, in TZS.', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price − discount.', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Product cost price at the time of sale.', max_digits=12)),
                ('line_cost', models.DecimalField(decimal_places=2, help_text='quantity × unit_cost.', max_digits=12)),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItemAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='catalog.productbatch')),
                ('business', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='accounts.business')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.saleitem')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'id'], name='customer_biz_id_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'name'], name='customer_biz_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('business', 'phone'), name='sales_customer_unique_phone_per_business'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'id'], name='sale_biz_id_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['business', 'created_at'], name='sale_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('business', 'number'), name='sales_sale_unique_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('discount_total__gte', 0), ('total__gte', 0), ('cost_total__gte', 0)), name='sales_sale_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount_total')))), name='sales_sale_total_is_subtotal_less_discount'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'id'], name='payment_biz_id_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'created_at'], name='payment_biz_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__gte', 0), ('change_given__gte', 0)), name='sales_payment_cash_not_negative'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['business', 'id'], name='saleitem_biz_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('unit_cost__gte', 0), ('discount__gte', 0)), name='sales_item_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')))), name='sales_item_discount_within_line'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), '-', models.F('discount')))), name='sales_item_line_total'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_cost', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_cost')))), name='sales_item_line_cost'),
        ),
        migrations.AddIndex(
            model_name='saleitemallocation',
            index=models.Index(fields=['business', 'id'], name='saleitemallocation_biz_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitemallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_allocation_quantity_positive'),
        ),
    ]
